/**
 * Tool-neutral agent document transformations: the Markdown → Codex TOML
 * transform and its read-back. Byte-for-byte twin of `cmx-core/src/agent.rs`;
 * the shared contract is pinned by the `agent-transform` conformance fixture.
 *
 * The frontmatter reader is a deliberate YAML *subset*: block, quoted, and
 * plain scalars for the five mapped top-level keys. It is dependency-free and
 * deterministic so both ports can match byte-for-byte.
 */

/** Frontmatter keys that become real TOML keys, in emission order. */
const MAPPED_KEYS = [
  "name",
  "description",
  "model",
  "model_reasoning_effort",
  "sandbox_mode",
] as const;
type MappedKey = (typeof MAPPED_KEYS)[number];

/** Mapped keys emitted only when present and non-empty. */
const OPTIONAL_KEYS = ["model", "model_reasoning_effort", "sandbox_mode"] as const;

/** The two prose lines that open a preserved-frontmatter block. */
const PRESERVED_HEADER = [
  "# Generated by cmx from a portable Markdown agent. Frontmatter Codex has no",
  "# key for is kept below as YAML so cmx can read it back; Codex ignores comments.",
] as const;

/** The comment line fencing the preserved YAML on both sides. */
const PRESERVED_FENCE = "# ---";

const splitMarkdown = (content: string): { frontmatter?: string; body: string } => {
  const open = content.startsWith("---\n")
    ? "---\n"
    : content.startsWith("---\r\n")
      ? "---\r\n"
      : undefined;
  if (open === undefined) return { body: content };
  const rest = content.slice(open.length);
  let lineStart = 0;
  while (lineStart <= rest.length) {
    const lineEnd = rest.indexOf("\n", lineStart);
    const hasNewline = lineEnd !== -1;
    const rawLine = rest.slice(lineStart, hasNewline ? lineEnd : rest.length);
    if (rawLine.replace(/\r$/u, "") === "---") {
      return {
        frontmatter: rest.slice(0, lineStart),
        body: hasNewline ? rest.slice(lineEnd + 1) : "",
      };
    }
    if (!hasNewline) break;
    lineStart = lineEnd + 1;
  }
  return { body: content };
};

// --- Line primitives -------------------------------------------------------

/** Split frontmatter inner text on `\n`, stripping one trailing `\r` per line. */
const frontmatterLines = (inner: string): string[] =>
  inner.split("\n").map((line) => (line.endsWith("\r") ? line.slice(0, -1) : line));

const isBlank = (line: string): boolean => line.trim().length === 0;

const startsWithIndent = (line: string): boolean => line.startsWith(" ") || line.startsWith("\t");

/** Whether `line` is a continuation of the entry above it: empty, or indented. */
const isContinuation = (line: string): boolean => line.length === 0 || startsWithIndent(line);

/** Whether `line` opens the top-level entry for `key`: `key:` then end-of-line, space, or tab. */
const opensEntry = (line: string, key: string): boolean => {
  if (!line.startsWith(`${key}:`)) return false;
  const next = line[key.length + 1];
  return next === undefined || next === " " || next === "\t";
};

const opensMappedEntry = (line: string): boolean =>
  MAPPED_KEYS.some((key) => opensEntry(line, key));

const continuationFrom = (lines: readonly string[], start: number): string[] => {
  const collected: string[] = [];
  for (let index = start; index < lines.length; index += 1) {
    const line = lines[index] ?? "";
    if (!isContinuation(line)) break;
    collected.push(line);
  }
  return collected;
};

const trimBlankEdges = (lines: readonly string[]): string[] => {
  let start = 0;
  let end = lines.length;
  while (start < end && isBlank(lines[start] ?? "")) start += 1;
  while (end > start && isBlank(lines[end - 1] ?? "")) end -= 1;
  return lines.slice(start, end);
};

// --- Block scalars ---------------------------------------------------------

/** `|` or `>`, optional chomping/indentation indicators, optional trailing comment. */
const BLOCK_INDICATOR = /^[|>][+\-0-9]*(?:[ \t]+#.*)?$/u;

const leadingSpaceCount = (line: string): number => line.length - line.replace(/^ */u, "").length;

/** Strip up to `indent` leading spaces from `line`. */
const stripIndent = (line: string, indent: number): string =>
  line.slice(Math.min(indent, leadingSpaceCount(line)));

/**
 * YAML `>` folding: a break between two plain lines becomes a space, an empty
 * line becomes a newline, and more-indented lines keep their breaks.
 */
const foldBlock = (lines: readonly string[]): string => {
  let out = lines[0] ?? "";
  for (let index = 1; index < lines.length; index += 1) {
    const line = lines[index] ?? "";
    const previous = lines[index - 1] ?? "";
    if (line === "") out += "\n";
    else if (previous === "") out += line;
    else if (startsWithIndent(line) || startsWithIndent(previous)) out += `\n${line}`;
    else out += ` ${line}`;
  }
  return out;
};

const blockScalar = (indicator: string, continuation: readonly string[]): string => {
  const firstContent = continuation.find((line) => !isBlank(line));
  const indent = firstContent === undefined ? 0 : leadingSpaceCount(firstContent);
  const content = continuation.map((line) => (isBlank(line) ? "" : stripIndent(line, indent)));
  while (content.at(-1) === "") content.pop();
  return indicator === "|" ? content.join("\n") : foldBlock(content);
};

// --- Flow scalars (quoted and plain) ---------------------------------------

/** One physical line of a flow scalar after unescaping. */
interface FlowPiece {
  readonly text: string;
  /** An escaped line break in a double-quoted scalar: join the successor with nothing. */
  readonly joinedToNext: boolean;
}

/**
 * Flow folding for lines that are already trimmed: a break between two
 * non-empty lines becomes a space, an empty line a newline, and a piece
 * marked `joinedToNext` joins its successor with nothing.
 */
const foldFlow = (pieces: readonly FlowPiece[]): string => {
  let out = pieces[0]?.text ?? "";
  for (let index = 1; index < pieces.length; index += 1) {
    const piece = pieces[index] ?? { text: "", joinedToNext: false };
    const previous = pieces[index - 1] ?? { text: "", joinedToNext: false };
    if (previous.joinedToNext) out += piece.text;
    else if (piece.text === "") out += "\n";
    else if (previous.text === "") out += piece.text;
    else out += ` ${piece.text}`;
  }
  return out;
};

type Quote = '"' | "'";

const DOUBLE_QUOTED_ESCAPES: Readonly<Record<string, string>> = {
  n: "\n",
  t: "\t",
  r: "\r",
  "0": "\0",
};

/** One unescaped physical line, and whether its closing quote was found. */
interface UnescapedLine {
  readonly piece: FlowPiece;
  readonly terminated: boolean;
}

/** Unescape one raw line of a quoted scalar up to its closing quote. */
const unescapeLine = (raw: string, quote: Quote): UnescapedLine => {
  let text = "";
  let index = 0;
  while (index < raw.length) {
    const character = raw[index] ?? "";
    const next = raw[index + 1];
    if (quote === '"' && character === "\\") {
      if (next === undefined) return { piece: { text, joinedToNext: true }, terminated: false };
      text += DOUBLE_QUOTED_ESCAPES[next] ?? next;
      index += 2;
    } else if (character === quote) {
      if (quote === "'" && next === "'") {
        text += "'";
        index += 2;
      } else {
        return { piece: { text, joinedToNext: false }, terminated: true };
      }
    } else {
      text += character;
      index += 1;
    }
  }
  return { piece: { text, joinedToNext: false }, terminated: false };
};

const trimPieceEnd = (piece: FlowPiece): FlowPiece => ({ ...piece, text: piece.text.trimEnd() });

/**
 * Read a quoted scalar whose opening quote has already been consumed from
 * `first`; `continuation` holds the entry's following lines. Scanning stops at
 * the closing quote; an unterminated scalar takes everything.
 */
const quotedScalar = (first: string, continuation: readonly string[], quote: Quote): string => {
  const rawLines = [first, ...continuation];
  const pieces: FlowPiece[] = [];
  for (let index = 0; index < rawLines.length; index += 1) {
    const raw = index === 0 ? (rawLines[index] ?? "") : (rawLines[index] ?? "").trimStart();
    const { piece, terminated } = unescapeLine(raw, quote);
    const isLast = terminated || index === rawLines.length - 1;
    pieces.push(isLast ? piece : trimPieceEnd(piece));
    if (terminated) break;
  }
  return foldFlow(pieces);
};

/** Drop a trailing `# comment`: a `#` at the start of the line or preceded by a space or tab. */
const stripComment = (line: string): string => {
  for (let index = 0; index < line.length; index += 1) {
    if (line[index] !== "#") continue;
    const previous = line[index - 1];
    if (previous === undefined || previous === " " || previous === "\t")
      return line.slice(0, index);
  }
  return line;
};

/** Read a plain scalar: comments stripped per line, then flow-folded. */
const plainScalar = (rest: string, continuation: readonly string[]): string =>
  foldFlow(
    [rest, ...continuation].map((line) => ({
      text: stripComment(line).trim(),
      joinedToNext: false,
    })),
  );

const readScalarValue = (rest: string, continuation: readonly string[]): string => {
  if (BLOCK_INDICATOR.test(rest)) return blockScalar(rest[0] ?? "|", continuation);
  if (rest.startsWith('"')) return quotedScalar(rest.slice(1), continuation, '"');
  if (rest.startsWith("'")) return quotedScalar(rest.slice(1), continuation, "'");
  return plainScalar(rest, continuation);
};

/** Read the scalar value of the top-level `key`, or `undefined` when absent. */
const scalar = (lines: readonly string[], key: MappedKey): string | undefined => {
  const start = lines.findIndex((line) => opensEntry(line, key));
  if (start === -1) return undefined;
  const rest = (lines[start] ?? "").slice(key.length + 1).trim();
  return readScalarValue(rest, continuationFrom(lines, start + 1)).trim();
};

// --- Preserved block -------------------------------------------------------

/**
 * The frontmatter lines that survive removing the mapped keys' entries, with
 * leading and trailing blank lines trimmed; empty when nothing survives.
 */
const preservedLines = (lines: readonly string[]): string[] => {
  const kept: string[] = [];
  let skipping = false;
  for (const line of lines) {
    if (!isContinuation(line)) skipping = opensMappedEntry(line);
    if (!skipping) kept.push(line);
  }
  return trimBlankEdges(kept);
};

const commentLine = (line: string): string => (isBlank(line) ? "#" : `# ${line}`);

const preservedBlock = (lines: readonly string[]): string[] => {
  const preserved = preservedLines(lines);
  if (preserved.length === 0) return [];
  return [...PRESERVED_HEADER, PRESERVED_FENCE, ...preserved.map(commentLine), PRESERVED_FENCE];
};

// --- TOML ------------------------------------------------------------------

const tomlString = (value: string): string => {
  let output = '"';
  for (const character of value) {
    switch (character) {
      case '"':
        output += '\\"';
        break;
      case "\\":
        output += "\\\\";
        break;
      case "\b":
        output += "\\b";
        break;
      case "\t":
        output += "\\t";
        break;
      case "\n":
        output += "\\n";
        break;
      case "\f":
        output += "\\f";
        break;
      case "\r":
        output += "\\r";
        break;
      default: {
        const codePoint = character.codePointAt(0) ?? 0;
        output +=
          codePoint < 0x20 || codePoint === 0x7f
            ? `\\u${codePoint.toString(16).toUpperCase().padStart(4, "0")}`
            : character;
      }
    }
  }
  return `${output}"`;
};

const tomlKeyValue = (key: string, value: string): string => `${key} = ${tomlString(value)}`;

const mappedKeyLines = (lines: readonly string[], fallbackName: string): string[] => {
  const out = [
    tomlKeyValue("name", scalar(lines, "name") || fallbackName),
    tomlKeyValue("description", scalar(lines, "description") ?? ""),
  ];
  for (const key of OPTIONAL_KEYS) {
    const value = scalar(lines, key);
    if (value !== undefined && value.length > 0) out.push(tomlKeyValue(key, value));
  }
  return out;
};

/**
 * Convert a markdown agent into Codex's TOML subagent format.
 *
 * Mapped frontmatter keys (`name`, `description`, `model`,
 * `model_reasoning_effort`, `sandbox_mode`) become TOML keys; `name` falls
 * back to `fallbackName` when absent or empty, `description` defaults to `""`,
 * and the remaining three are omitted when absent or empty. The markdown body
 * (trailing newlines trimmed) becomes `developer_instructions`, always last.
 *
 * Whatever frontmatter is left once the mapped entries are removed is emitted
 * first, as a `# ---`-fenced comment block that {@link preservedFrontmatter}
 * reads back. Codex rejects unknown keys, so nothing else is ever emitted as a
 * key. A document without frontmatter, or whose frontmatter holds only mapped
 * keys, gets no such block.
 */
export const markdownToCodexToml = (markdown: string, fallbackName: string): string => {
  const { frontmatter, body } = splitMarkdown(markdown);
  const lines = frontmatter === undefined ? [] : frontmatterLines(frontmatter);
  const out = [
    ...preservedBlock(lines),
    ...mappedKeyLines(lines, fallbackName),
    tomlKeyValue("developer_instructions", body.replace(/\n+$/u, "")),
  ];
  return `${out.join("\n")}\n`;
};

const uncomment = (line: string): string | undefined => {
  if (!line.startsWith("#")) return undefined;
  return line.startsWith("# ") ? line.slice(2) : line.slice(1);
};

/**
 * Read back the YAML frontmatter that {@link markdownToCodexToml} preserved in
 * a generated Codex agent.
 *
 * Returns the text between the first `# ---` line and the next one, with the
 * leading `# ` (or bare `#`) stripped from every line and a trailing newline
 * appended — the frontmatter *inner* text, ready for a version reader.
 * `undefined` when there is no opening `# ---`, no closing one, or any line
 * between them is not a comment.
 */
export const preservedFrontmatter = (toml: string): string | undefined => {
  const lines = toml.split("\n");
  const open = lines.indexOf(PRESERVED_FENCE);
  if (open === -1) return undefined;
  const close = lines.indexOf(PRESERVED_FENCE, open + 1);
  if (close === -1) return undefined;
  let inner = "";
  for (const line of lines.slice(open + 1, close)) {
    const content = uncomment(line);
    if (content === undefined) return undefined;
    inner += `${content}\n`;
  }
  return inner;
};
