import { describe, expect, test } from "bun:test";

import { markdownToCodexToml, preservedFrontmatter } from "../src/agent.ts";

const HEADER =
  "# Generated by cmx from a portable Markdown agent. Frontmatter Codex has no\n" +
  "# key for is kept below as YAML so cmx can read it back; Codex ignores comments.\n";

const agent = (frontmatter: string, body = "Body.\n"): string => `---\n${frontmatter}---\n${body}`;

const descriptionOf = (frontmatter: string): string => {
  const line = markdownToCodexToml(agent(frontmatter), "fallback")
    .split("\n")
    .find((candidate) => candidate.startsWith("description = "));
  if (line === undefined) throw new Error("description line missing");
  return JSON.parse(line.slice("description = ".length)) as string;
};

describe("markdownToCodexToml", () => {
  test("emits mapped keys in order and developer_instructions last", () => {
    const markdown = agent(
      "sandbox_mode: workspace-write\nmodel_reasoning_effort: high\nmodel: gpt-5\ndescription: Helps\nname: helper\n",
      "Be helpful.\n\n",
    );
    expect(markdownToCodexToml(markdown, "fallback")).toBe(
      'name = "helper"\n' +
        'description = "Helps"\n' +
        'model = "gpt-5"\n' +
        'model_reasoning_effort = "high"\n' +
        'sandbox_mode = "workspace-write"\n' +
        'developer_instructions = "Be helpful."\n',
    );
  });

  test("falls back to the fallback name and omits empty optional keys", () => {
    const markdown = agent("name:\nmodel: ''\nsandbox_mode:   # nothing\n");
    expect(markdownToCodexToml(markdown, "fallback")).toBe(
      'name = "fallback"\ndescription = ""\ndeveloper_instructions = "Body."\n',
    );
  });

  test("without frontmatter the whole document is the body and nothing is preserved", () => {
    expect(markdownToCodexToml("one\ntwo\n", "reviewer")).toBe(
      'name = "reviewer"\ndescription = ""\ndeveloper_instructions = "one\\ntwo"\n',
    );
  });

  test("frontmatter with only mapped keys emits no preserved block", () => {
    const out = markdownToCodexToml(agent("name: helper\ndescription: Helps\n"), "fallback");
    expect(out.startsWith('name = "helper"\n')).toBe(true);
    expect(preservedFrontmatter(out)).toBeUndefined();
  });

  test("keeps unmapped entries, comments, and blank lines in the preserved block", () => {
    const markdown = agent(
      '# top comment\nname: helper\ndescription: |\n  Long.\n\n  Text.\nmetadata:\n  version: "1.3.0"\n\n  author: Stacey\ntools: [a, b]\nmodel: gpt-5\n',
    );
    expect(markdownToCodexToml(markdown, "fallback")).toBe(
      `${HEADER}# ---\n` +
        "# # top comment\n" +
        "# metadata:\n" +
        '#   version: "1.3.0"\n' +
        "#\n" +
        "#   author: Stacey\n" +
        "# tools: [a, b]\n" +
        "# ---\n" +
        'name = "helper"\n' +
        'description = "Long.\\n\\nText."\n' +
        'model = "gpt-5"\n' +
        'developer_instructions = "Body."\n',
    );
  });

  test("does not treat a longer key with a mapped prefix as mapped", () => {
    const out = markdownToCodexToml(agent("name: helper\nname_extra: x\nmodel-x: y\n"), "f");
    expect(preservedFrontmatter(out)).toBe("name_extra: x\nmodel-x: y\n");
  });

  test("normalizes CRLF frontmatter to LF output; the body keeps its bytes", () => {
    const markdown =
      "---\r\nname: helper\r\ndescription: >\r\n  a\r\n  b\r\nmetadata:\r\n  v: 1\r\n---\r\nline one\r\nline two\r\n";
    expect(markdownToCodexToml(markdown, "fallback")).toBe(
      `${HEADER}# ---\n# metadata:\n#   v: 1\n# ---\n` +
        'name = "helper"\n' +
        'description = "a b"\n' +
        'developer_instructions = "line one\\r\\nline two\\r"\n',
    );
  });
});

describe("scalar reading", () => {
  test("literal block scalar keeps line breaks and interior blank lines", () => {
    expect(descriptionOf("description: |\n  Reviews code.\n\n  Use when needed.\n\n")).toBe(
      "Reviews code.\n\nUse when needed.",
    );
  });

  test("block scalar chomping and indentation indicators are accepted and ignored", () => {
    expect(descriptionOf("description: |+2  # keep\n  one\n  two\n\n")).toBe("one\ntwo");
    expect(descriptionOf("description: >-\n  one\n  two\n")).toBe("one two");
  });

  test("block scalar with no content lines is empty", () => {
    expect(descriptionOf("description: |\nmodel: x\n")).toBe("");
  });

  test("folded block scalar joins lines, keeps blank lines, and respects more-indented lines", () => {
    expect(descriptionOf("description: >\n  a\n  b\n\n  c\n    d\n    e\n  f\n")).toBe(
      "a b\nc\n  d\n  e\nf",
    );
  });

  test("double-quoted scalar folds lines and decodes escapes", () => {
    expect(
      descriptionOf(
        'description: "Line \\"one\\"\\tTab\\n\n\n  two \\\n  three\\\\ end" # trailing\n',
      ),
    ).toBe('Line "one"\tTab\ntwothree\\ end');
  });

  test("double-quoted scalar ignores text after the closing quote and tolerates being unterminated", () => {
    expect(descriptionOf('description: "abc" def\n')).toBe("abc");
    expect(descriptionOf('description: "abc\n  def\nmodel: x\n')).toBe("abc def");
    expect(descriptionOf('description: "\\/\\ \\q"\n')).toBe("/ q");
  });

  test("double-quoted escapes decode before the break trims, and an escaped break joins across an empty line", () => {
    expect(descriptionOf('description: "a\\t\n  b"\n')).toBe("a b");
    expect(descriptionOf('description: "abc\\\n\n  def"\n')).toBe("abcdef");
  });

  test("single-quoted scalar decodes only the doubled quote", () => {
    expect(descriptionOf("description: 'it''s \\n raw\n  next' ignored\n")).toBe(
      "it's \\n raw next",
    );
  });

  test("plain scalar strips trailing comments and folds continuation lines", () => {
    expect(descriptionOf("description: one # note\n  two#not-a-comment\n  three\n")).toBe(
      "one two#not-a-comment three",
    );
    // A whole-line comment strips to an empty line, which folds to a newline.
    expect(descriptionOf("description: one\n  # gone\n  two\n")).toBe("one\ntwo");
    expect(descriptionOf("description:\n  starts below\n")).toBe("starts below");
  });

  test("plain scalar no longer strips surrounding quotes blindly", () => {
    expect(descriptionOf('description: say "hi"\n')).toBe('say "hi"');
  });

  test("the first matching top-level key wins", () => {
    expect(descriptionOf("description: first\ndescription: second\n")).toBe("first");
  });
});

describe("preservedFrontmatter", () => {
  test("round-trips the preserved block as frontmatter inner text", () => {
    const inner = 'metadata:\n  author: Fixture Author\n  version: "2.4.6"\n';
    const out = markdownToCodexToml(agent(`name: a\n${inner}`), "a");
    expect(preservedFrontmatter(out)).toBe(inner);
  });

  test("round-trips blank lines and nested comment lines", () => {
    const inner = "# note\nmetadata:\n\n  v: 1\n";
    const out = markdownToCodexToml(agent(`name: a\n${inner}`), "a");
    expect(preservedFrontmatter(out)).toBe(inner);
  });

  test("returns undefined when there is no block, no closing fence, or an uncommented line", () => {
    expect(preservedFrontmatter('name = "a"\n')).toBeUndefined();
    expect(preservedFrontmatter("# ---\n# metadata:\n")).toBeUndefined();
    expect(preservedFrontmatter('# ---\nname = "a"\n# ---\n')).toBeUndefined();
  });

  test("strips a bare hash, and an empty block reads back as empty text", () => {
    expect(preservedFrontmatter("# ---\n#a\n#\n# ---\n")).toBe("a\n\n");
    expect(preservedFrontmatter("# ---\n# ---\n")).toBe("");
  });
});
