//! Tool-neutral agent document transformations.
//!
//! The one transform today is Markdown → Codex subagent TOML. Codex parses
//! `~/.codex/agents/*.toml` with `deny_unknown_fields`, so the generated
//! document may carry only keys Codex defines: the required `name`,
//! `description`, and `developer_instructions`, plus config keys such as
//! `model`. Everything else in the source frontmatter — `metadata.version`
//! above all — is kept inside a comment block so cmx can read it back
//! ([`preserved_frontmatter`]) while Codex ignores it.
//!
//! The frontmatter reader here is a deliberate YAML *subset*: block scalars,
//! quoted scalars, and plain scalars for the five mapped top-level keys. It is
//! dependency-free and deterministic so the TypeScript port can match it
//! byte-for-byte (the `agent-transform` conformance fixtures pin the result).

use crate::frontmatter::split_frontmatter_spans;

/// Frontmatter keys that become real TOML keys, in emission order.
const MAPPED_KEYS: [&str; 5] = [
    "name",
    "description",
    "model",
    "model_reasoning_effort",
    "sandbox_mode",
];

/// Mapped keys emitted only when present and non-empty (after `name` and
/// `description`, which are always emitted).
const OPTIONAL_KEYS: [&str; 3] = ["model", "model_reasoning_effort", "sandbox_mode"];

/// The two prose lines that open a preserved-frontmatter block.
const PRESERVED_HEADER: &str = "# Generated by cmx from a portable Markdown agent. Frontmatter Codex has no\n\
                                # key for is kept below as YAML so cmx can read it back; Codex ignores comments.\n";

/// The comment line fencing the preserved YAML on both sides.
const PRESERVED_FENCE: &str = "# ---";

/// Convert a markdown agent into Codex's TOML subagent format.
///
/// Mapped frontmatter keys (`name`, `description`, `model`,
/// `model_reasoning_effort`, `sandbox_mode`) become TOML keys; `name` falls
/// back to `fallback_name` when absent or empty, `description` defaults to `""`,
/// and the remaining three are omitted when absent or empty. The markdown body
/// (trailing newlines trimmed) becomes `developer_instructions`, always last.
///
/// Whatever frontmatter is left once the mapped entries are removed is emitted
/// first, as a `# ---`-fenced comment block that [`preserved_frontmatter`]
/// reads back. A document without frontmatter, or whose frontmatter holds only
/// mapped keys, gets no such block.
pub fn markdown_to_codex_toml(markdown: &str, fallback_name: &str) -> String {
    let (frontmatter, body) = split_markdown(markdown);
    let lines = frontmatter.map(frontmatter_lines).unwrap_or_default();

    let name = scalar(&lines, "name")
        .filter(|v| !v.is_empty())
        .unwrap_or_else(|| fallback_name.to_string());
    let description = scalar(&lines, "description").unwrap_or_default();

    let mut out = String::new();
    if let Some(preserved) = preserved_lines(&lines) {
        out.push_str(PRESERVED_HEADER);
        out.push_str(PRESERVED_FENCE);
        out.push('\n');
        for line in preserved {
            if line.trim().is_empty() {
                out.push('#');
            } else {
                out.push_str("# ");
                out.push_str(line);
            }
            out.push('\n');
        }
        out.push_str(PRESERVED_FENCE);
        out.push('\n');
    }
    out.push_str(&toml_kv("name", &name));
    out.push_str(&toml_kv("description", &description));
    for key in OPTIONAL_KEYS {
        if let Some(value) = scalar(&lines, key).filter(|v| !v.is_empty()) {
            out.push_str(&toml_kv(key, &value));
        }
    }
    out.push_str(&toml_kv("developer_instructions", body.trim_end_matches('\n')));
    out
}

/// Read back the YAML frontmatter that [`markdown_to_codex_toml`] preserved in
/// a generated Codex agent.
///
/// Returns the text between the first `# ---` line and the next one, with the
/// leading `# ` (or bare `#`) stripped from every line and a trailing newline
/// appended — the frontmatter *inner* text, ready for a version reader. Returns
/// `None` when there is no opening `# ---`, no closing one, or any line between
/// them is not a comment.
pub fn preserved_frontmatter(toml: &str) -> Option<String> {
    let mut lines = toml.split('\n');
    lines.find(|line| *line == PRESERVED_FENCE)?;
    let mut inner = String::new();
    for line in lines {
        if line == PRESERVED_FENCE {
            return Some(inner);
        }
        let content = line.strip_prefix("# ").or_else(|| line.strip_prefix('#'))?;
        inner.push_str(content);
        inner.push('\n');
    }
    None
}

fn split_markdown(content: &str) -> (Option<&str>, &str) {
    let Some(spans) = split_frontmatter_spans(content) else {
        return (None, content);
    };
    let body = spans
        .closing_and_body
        .strip_prefix("---\r\n")
        .or_else(|| spans.closing_and_body.strip_prefix("---\n"))
        .unwrap_or("");
    (Some(spans.inner), body)
}

/// Split frontmatter inner text on `\n`, stripping one trailing `\r` per line.
fn frontmatter_lines(inner: &str) -> Vec<&str> {
    inner.split('\n').map(|line| line.strip_suffix('\r').unwrap_or(line)).collect()
}

/// Whether `line` is a continuation of the entry above it: blank, or indented.
fn is_continuation(line: &str) -> bool {
    line.is_empty() || line.starts_with([' ', '\t'])
}

/// Whether `line` opens the top-level entry for `key`: `key:` followed by
/// end-of-line, a space, or a tab.
fn opens_entry(line: &str, key: &str) -> bool {
    line.strip_prefix(key)
        .and_then(|rest| rest.strip_prefix(':'))
        .is_some_and(|rest| rest.is_empty() || rest.starts_with([' ', '\t']))
}

/// The frontmatter lines that survive removing the mapped keys' entries, with
/// leading and trailing blank lines trimmed; `None` when nothing survives.
fn preserved_lines<'a>(lines: &[&'a str]) -> Option<Vec<&'a str>> {
    let mut kept: Vec<&'a str> = Vec::new();
    let mut skipping = false;
    for line in lines {
        if !is_continuation(line) {
            skipping = MAPPED_KEYS.iter().any(|key| opens_entry(line, key));
        }
        if !skipping {
            kept.push(line);
        }
    }
    let first = kept.iter().position(|line| !line.trim().is_empty())?;
    let last = kept.iter().rposition(|line| !line.trim().is_empty())?;
    Some(kept[first..=last].to_vec())
}

/// Read the scalar value of the top-level `key`, or `None` when absent.
fn scalar(lines: &[&str], key: &str) -> Option<String> {
    let start = lines.iter().position(|line| opens_entry(line, key))?;
    let rest = lines[start][key.len() + 1..].trim();
    let continuation: Vec<&str> = lines[start + 1..]
        .iter()
        .copied()
        .take_while(|line| is_continuation(line))
        .collect();

    let value = if let Some(style) = block_style(rest) {
        block_scalar(style, &continuation)
    } else if let Some(inner) = rest.strip_prefix('"') {
        quoted_scalar(inner, &continuation, Quote::Double)
    } else if let Some(inner) = rest.strip_prefix('\'') {
        quoted_scalar(inner, &continuation, Quote::Single)
    } else {
        plain_scalar(rest, &continuation)
    };
    Some(value.trim().to_string())
}

#[derive(Clone, Copy)]
enum BlockStyle {
    Literal,
    Folded,
}

/// `Some(style)` when `rest` is a block-scalar indicator (`|` or `>`, optional
/// chomping/indentation digits, optional trailing comment).
fn block_style(rest: &str) -> Option<BlockStyle> {
    let (style, tail) = match rest.chars().next()? {
        '|' => (BlockStyle::Literal, &rest[1..]),
        '>' => (BlockStyle::Folded, &rest[1..]),
        _ => return None,
    };
    let tail =
        tail.trim_start_matches(['+', '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']);
    let is_indicator_only =
        tail.is_empty() || (tail.starts_with([' ', '\t']) && tail.trim_start().starts_with('#'));
    is_indicator_only.then_some(style)
}

fn block_scalar(style: BlockStyle, continuation: &[&str]) -> String {
    let indent = continuation
        .iter()
        .find(|line| !line.trim().is_empty())
        .map_or(0, |line| line.len() - line.trim_start_matches(' ').len());
    let mut content: Vec<&str> = continuation
        .iter()
        .map(|line| {
            if line.trim().is_empty() {
                ""
            } else {
                strip_indent(line, indent)
            }
        })
        .collect();
    while content.last().is_some_and(|line| line.is_empty()) {
        content.pop();
    }
    match style {
        BlockStyle::Literal => content.join("\n"),
        BlockStyle::Folded => fold_block(&content),
    }
}

/// Strip up to `indent` leading spaces from `line`.
fn strip_indent(line: &str, indent: usize) -> &str {
    let available = line.len() - line.trim_start_matches(' ').len();
    &line[available.min(indent)..]
}

/// YAML `>` folding: a break between two plain lines becomes a space, an
/// empty line becomes a newline, and more-indented lines keep their breaks.
fn fold_block(lines: &[&str]) -> String {
    let Some((first, tail)) = lines.split_first() else {
        return String::new();
    };
    let mut out = (*first).to_string();
    let mut previous = *first;
    for line in tail {
        if line.is_empty() {
            out.push('\n');
        } else if previous.is_empty() {
            out.push_str(line);
        } else if line.starts_with([' ', '\t']) || previous.starts_with([' ', '\t']) {
            out.push('\n');
            out.push_str(line);
        } else {
            out.push(' ');
            out.push_str(line);
        }
        previous = line;
    }
    out
}

/// Flow folding for quoted and plain scalars, whose lines are already trimmed:
/// a break between two non-empty lines becomes a space, an empty line a newline.
/// A piece marked `joined_to_next` (an escaped line break in a double-quoted
/// scalar) joins its successor with nothing.
fn fold_flow(pieces: &[FlowPiece]) -> String {
    let Some((first, tail)) = pieces.split_first() else {
        return String::new();
    };
    let mut out = first.text.clone();
    let mut previous = first;
    for piece in tail {
        if previous.joined_to_next {
            out.push_str(&piece.text);
        } else if piece.text.is_empty() {
            out.push('\n');
        } else if previous.text.is_empty() {
            out.push_str(&piece.text);
        } else {
            out.push(' ');
            out.push_str(&piece.text);
        }
        previous = piece;
    }
    out
}

/// One physical line of a flow scalar after unescaping.
struct FlowPiece {
    text: String,
    joined_to_next: bool,
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Quote {
    Double,
    Single,
}

/// Read a quoted scalar whose opening quote has already been consumed from
/// `first`; `continuation` holds the entry's following lines. Scanning stops at
/// the closing quote; an unterminated scalar takes everything.
fn quoted_scalar(first: &str, continuation: &[&str], quote: Quote) -> String {
    let mut pieces = Vec::new();
    let mut raw_lines = std::iter::once(first).chain(continuation.iter().copied()).peekable();
    let mut index = 0;
    while let Some(raw) = raw_lines.next() {
        let raw = if index == 0 { raw } else { raw.trim_start() };
        let (piece, terminated) = unescape_line(raw, quote);
        let is_last = terminated || raw_lines.peek().is_none();
        pieces.push(if is_last {
            piece
        } else {
            trim_piece_end(piece)
        });
        if terminated {
            break;
        }
        index += 1;
    }
    fold_flow(&pieces)
}

/// Unescape one raw line of a quoted scalar up to its closing quote. Returns
/// the piece and whether the closing quote was found on this line.
fn unescape_line(raw: &str, quote: Quote) -> (FlowPiece, bool) {
    let mut text = String::new();
    let mut joined_to_next = false;
    let mut chars = raw.chars().peekable();
    while let Some(ch) = chars.next() {
        match (quote, ch) {
            (Quote::Double, '"') => {
                return (
                    FlowPiece {
                        text,
                        joined_to_next,
                    },
                    true,
                );
            }
            (Quote::Double, '\\') => match chars.next() {
                None => joined_to_next = true,
                Some(escaped) => text.push(unescape_double(escaped)),
            },
            (Quote::Single, '\'') => {
                if chars.peek() == Some(&'\'') {
                    chars.next();
                    text.push('\'');
                } else {
                    return (
                        FlowPiece {
                            text,
                            joined_to_next,
                        },
                        true,
                    );
                }
            }
            (_, c) => text.push(c),
        }
    }
    (
        FlowPiece {
            text,
            joined_to_next,
        },
        false,
    )
}

fn unescape_double(escaped: char) -> char {
    match escaped {
        'n' => '\n',
        't' => '\t',
        'r' => '\r',
        '0' => '\0',
        other => other,
    }
}

/// Trim trailing whitespace from a piece that is followed by a line break.
fn trim_piece_end(mut piece: FlowPiece) -> FlowPiece {
    piece.text.truncate(piece.text.trim_end().len());
    piece
}

/// Read a plain scalar: comments stripped per line, then flow-folded.
fn plain_scalar(rest: &str, continuation: &[&str]) -> String {
    let pieces: Vec<FlowPiece> = std::iter::once(rest)
        .chain(continuation.iter().copied())
        .map(|line| FlowPiece {
            text: strip_comment(line).trim().to_string(),
            joined_to_next: false,
        })
        .collect();
    fold_flow(&pieces)
}

/// Drop a trailing `# comment`: a `#` at the start of the line or preceded by
/// whitespace, and everything after it.
fn strip_comment(line: &str) -> &str {
    let mut previous: Option<char> = None;
    for (idx, ch) in line.char_indices() {
        if ch == '#' && previous.is_none_or(|p| p == ' ' || p == '\t') {
            return &line[..idx];
        }
        previous = Some(ch);
    }
    line
}

fn toml_kv(key: &str, value: &str) -> String {
    format!("{key} = {}\n", toml_basic_string(value))
}

fn toml_basic_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\u{08}' => out.push_str("\\b"),
            '\u{0c}' => out.push_str("\\f"),
            c if (c as u32) < 0x20 || (c as u32) == 0x7f => {
                use std::fmt::Write as _;
                let _ = write!(out, "\\u{:04X}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const HEADER: &str = "# Generated by cmx from a portable Markdown agent. Frontmatter Codex has no\n\
                          # key for is kept below as YAML so cmx can read it back; Codex ignores comments.\n";

    fn doc(frontmatter: &str) -> String {
        format!("---\n{frontmatter}---\nBody.\n")
    }

    fn description_of(frontmatter: &str) -> String {
        let lines = frontmatter_lines(frontmatter);
        scalar(&lines, "description").expect("description present")
    }

    // --- whole-document shape ---

    #[test]
    fn converts_markdown_to_codex_toml() {
        let markdown = "---\nname: reviewer\ndescription: Reviews code\nmodel: gpt-5\n---\nReview carefully.\n";
        let out = markdown_to_codex_toml(markdown, "fallback");
        assert_eq!(
            out,
            "name = \"reviewer\"\ndescription = \"Reviews code\"\nmodel = \"gpt-5\"\n\
             developer_instructions = \"Review carefully.\"\n"
        );
    }

    #[test]
    fn escapes_multiline_instructions() {
        let out = markdown_to_codex_toml("one\ntwo\n", "reviewer");
        assert_eq!(
            out,
            "name = \"reviewer\"\ndescription = \"\"\ndeveloper_instructions = \"one\\ntwo\"\n"
        );
    }

    #[test]
    fn no_frontmatter_uses_fallback_and_whole_body() {
        let out = markdown_to_codex_toml("# Heading\n\nText.\n\n", "helper");
        assert!(!out.contains("# ---"), "no preserved block: {out}");
        assert!(out.starts_with("name = \"helper\"\n"), "{out}");
        assert!(out.contains("developer_instructions = \"# Heading\\n\\nText.\""), "{out}");
    }

    #[test]
    fn only_mapped_keys_emits_no_preserved_block() {
        let out = markdown_to_codex_toml(
            &doc(
                "name: a\ndescription: b\nmodel: m\nmodel_reasoning_effort: high\nsandbox_mode: read-only\n",
            ),
            "x",
        );
        assert_eq!(
            out,
            "name = \"a\"\ndescription = \"b\"\nmodel = \"m\"\nmodel_reasoning_effort = \"high\"\n\
             sandbox_mode = \"read-only\"\ndeveloper_instructions = \"Body.\"\n"
        );
    }

    #[test]
    fn empty_optional_keys_are_omitted_and_empty_name_falls_back() {
        let out = markdown_to_codex_toml(&doc("name:\nmodel: \nsandbox_mode: ''\n"), "fb");
        assert_eq!(out, "name = \"fb\"\ndescription = \"\"\ndeveloper_instructions = \"Body.\"\n");
    }

    #[test]
    fn preserved_block_keeps_unmapped_entries_with_exact_header() {
        let out = markdown_to_codex_toml(
            &doc(
                "name: a\nmetadata:\n  version: \"1.3.0\"\n  author: Stacey Vetzal\ndescription: d\n",
            ),
            "x",
        );
        let expected = format!(
            "{HEADER}# ---\n# metadata:\n#   version: \"1.3.0\"\n#   author: Stacey Vetzal\n# ---\n\
             name = \"a\"\ndescription = \"d\"\ndeveloper_instructions = \"Body.\"\n"
        );
        assert_eq!(out, expected);
    }

    #[test]
    fn preserved_block_blank_line_is_bare_hash_and_comments_survive() {
        // The blank line belongs to the comment entry (unmapped), so it is kept;
        // the blank line after `name:` is that mapped entry's continuation and goes.
        let out = markdown_to_codex_toml(&doc("\n# top comment\n\nname: a\n\ntools: [x]\n\n"), "x");
        assert!(out.contains("# ---\n# # top comment\n#\n# tools: [x]\n# ---\n"), "{out}");
    }

    #[test]
    fn mapped_entry_removal_takes_its_continuation_lines() {
        let out = markdown_to_codex_toml(
            &doc(
                "description: |\n  one\n\n  two\nextra: yes\nname: n\n  # indented comment under name\n",
            ),
            "x",
        );
        assert!(out.contains("# ---\n# extra: yes\n# ---\n"), "{out}");
        assert!(out.contains("description = \"one\\n\\ntwo\""), "{out}");
    }

    #[test]
    fn key_prefix_does_not_match_longer_key() {
        let out = markdown_to_codex_toml(&doc("model_name: other\nmodel:gpt\nname: n\n"), "x");
        assert!(out.contains("# model_name: other\n# model:gpt\n"), "{out}");
        assert!(!out.contains("model = "), "{out}");
    }

    #[test]
    fn crlf_input_emits_lf_only() {
        let md = "---\r\nname: x\r\ndescription: |\r\n  Foo\r\n  Bar\r\nmetadata:\r\n  version: \"1.0.0\"\r\n---\r\nBody\r\n";
        let out = markdown_to_codex_toml(md, "fb");
        assert!(out.contains("# ---\n# metadata:\n#   version: \"1.0.0\"\n# ---\n"), "{out}");
        assert!(out.contains("description = \"Foo\\nBar\""), "{out}");
        assert!(!out.contains("\r\n"), "no CRLF line endings: {out}");
    }

    // --- block scalars ---

    #[test]
    fn literal_block_keeps_newlines_and_blank_lines() {
        assert_eq!(description_of("description: |\n  one\n\n  two\n"), "one\n\ntwo");
    }

    #[test]
    fn literal_block_with_chomping_and_comment_indicators() {
        assert_eq!(description_of("description: |- # note\n  one\n  two\n\n\n"), "one\ntwo");
        assert_eq!(description_of("description: |+\n  one\n"), "one");
        assert_eq!(description_of("description: >2\n  one\n  two\n"), "one two");
    }

    #[test]
    fn literal_block_without_content_is_empty() {
        assert_eq!(description_of("description: |\n"), "");
        assert_eq!(description_of("description: |\n\nname: x\n"), "");
    }

    #[test]
    fn folded_block_joins_with_spaces_and_keeps_paragraphs() {
        assert_eq!(description_of("description: >\n  one\n  two\n\n  three\n"), "one two\nthree");
    }

    #[test]
    fn folded_block_keeps_more_indented_lines() {
        assert_eq!(
            description_of("description: >\n  intro\n    code\n    more\n  outro\n"),
            "intro\n  code\n  more\noutro"
        );
    }

    #[test]
    fn block_indent_is_taken_from_first_nonblank_line() {
        assert_eq!(description_of("description: |\n\n    deep\n  shallow\n"), "deep\nshallow");
    }

    #[test]
    fn indicator_followed_by_text_is_a_plain_scalar() {
        assert_eq!(description_of("description: >= 2.0 required\n"), ">= 2.0 required");
        assert_eq!(description_of("description: |pipe\n"), "|pipe");
    }

    // --- double-quoted ---

    #[test]
    fn double_quoted_resolves_escapes_and_ignores_trailing_text() {
        assert_eq!(
            description_of("description: \"a \\\"b\\\"\\n\\t\\\\ \\/x\\ y\" # after\n"),
            "a \"b\"\n\t\\ /x y"
        );
    }

    #[test]
    fn double_quoted_multi_line_folds() {
        assert_eq!(
            description_of("description: \"one  \n   two\n\n  three\"\nname: n\n"),
            "one two\nthree"
        );
    }

    #[test]
    fn double_quoted_escaped_line_break_joins_with_nothing() {
        assert_eq!(description_of("description: \"one\\\n  two\"\n"), "onetwo");
    }

    #[test]
    fn double_quoted_unterminated_takes_everything() {
        assert_eq!(description_of("description: \"one\n  two\nname: n\n"), "one two");
    }

    #[test]
    fn double_quoted_unknown_escape_yields_the_char() {
        assert_eq!(description_of("description: \"\\q\\0\"\n"), "q\0");
    }

    // --- single-quoted ---

    #[test]
    fn single_quoted_only_escape_is_doubled_quote() {
        assert_eq!(description_of("description: 'it''s \\n raw' # c\n"), "it's \\n raw");
    }

    #[test]
    fn single_quoted_multi_line_folds() {
        assert_eq!(description_of("description: 'one\n  two\n\n  three'\n"), "one two\nthree");
    }

    // --- plain ---

    #[test]
    fn plain_strips_trailing_comment_but_keeps_inline_hash() {
        assert_eq!(description_of("description: issue#1 wins # not this\n"), "issue#1 wins");
        assert_eq!(description_of("description: # only a comment\n"), "");
    }

    #[test]
    fn plain_multi_line_folds_with_continuations() {
        assert_eq!(
            description_of("description: one\n  two # c\n\n  three\nname: n\n"),
            "one two\nthree"
        );
    }

    #[test]
    fn plain_empty_value_is_empty() {
        assert_eq!(description_of("description:\nname: n\n"), "");
        assert_eq!(description_of("description:   \n"), "");
    }

    #[test]
    fn scalar_takes_first_top_level_match_only() {
        let lines = frontmatter_lines("name: first\nnested:\n  name: inner\nname: second\n");
        assert_eq!(scalar(&lines, "name").as_deref(), Some("first"));
        assert_eq!(scalar(&lines, "missing"), None);
    }

    // --- read-back ---

    #[test]
    fn preserved_frontmatter_round_trips() {
        let md = doc("name: a\nmetadata:\n  version: \"1.3.0\"\n\n  author: me\ndescription: d\n");
        let toml = markdown_to_codex_toml(&md, "x");
        assert_eq!(
            preserved_frontmatter(&toml).as_deref(),
            Some("metadata:\n  version: \"1.3.0\"\n\n  author: me\n")
        );
    }

    #[test]
    fn preserved_frontmatter_none_without_block() {
        assert_eq!(preserved_frontmatter("name = \"a\"\n"), None);
        assert_eq!(preserved_frontmatter("# ---\n# metadata:\nname = \"a\"\n"), None, "unclosed");
        assert_eq!(preserved_frontmatter("# ---\nname = \"a\"\n# ---\n"), None, "non-comment line");
    }

    #[test]
    fn preserved_frontmatter_strips_bare_hash_and_hash_space() {
        assert_eq!(
            preserved_frontmatter("# ---\n#x\n#\n#  y\n# ---\n").as_deref(),
            Some("x\n\n y\n")
        );
    }
}
